# Generated by Django 5.1.2 on 2024-10-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='BulkProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.product')),
                ('bulk_quantity', models.PositiveIntegerField()),
                ('bulk_discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'bulk_product',
            },
            bases=('pricing.product',),
        ),
        migrations.CreateModel(
            name='SeasonalProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.product')),
                ('season_discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'seasonal_product',
            },
            bases=('pricing.product',),
        ),
        migrations.CreateModel(
            name='FixedAmountDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.discount')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'fixedAmount_discount',
            },
            bases=('pricing.discount',),
        ),
        migrations.CreateModel(
            name='PercentageDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.discount')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'percentage_discount',
            },
            bases=('pricing.discount',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bulk_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.bulkproduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.seasonalproduct')),
                ('fixed_amount_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.fixedamountdiscount')),
                ('percentage_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.percentagediscount')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
